build:
	docker build -t deltachat/debian-stretch-node-11 .

build-next:
	docker build -t deltachat/debian-stretch-node-11:next .

push:
	docker push deltachat/debian-stretch-node-11:latest

push-next:
	docker push deltachat/debian-stretch-node-11:next
